site:
    class: Statocles::Site
    args:
        title: (R)?ex, the friendly automation framework
        markdown:
            $class: Text::MultiMarkdown
        base_url: https://www.rexify.org
        theme:
            $ref: rexify
        apps:
            basic:
                $ref: basic_app
            blog:
                $ref: blog
            public:
                $ref: public
        plugins:
            highlight:
                $class: Statocles::Plugin::Highlight::RexOps
            link_check:
                $class: Statocles::Plugin::LinkCheck
            lint:
                $class: Statocles::Plugin::HTMLLint
                fatal: 1
                plugins:
                    - HTML5
                    - RDFa
                    - TinyEntitesEscapeRule
        deploy:
            $ref: gh_pages
        data:
            nav:
                - title: Home
                  url: /
                - url: /get/index.html
                  title: Get Rex
                - url: /care/index.html
                  title: Care
                  children:
                      - url: /care/help__r__ex.html
                        title: Help (R)?ex
                      - url: /care/help_people_in_need.html
                        title: Help people
                - url: /support/index.html
                  title: Support
                - url: /docs/index.html
                  title: Docs
                  children:
                      - url: /docs/faq/index.html
                        title: FAQ
                      - url: /docs/guides/index.html
                        title: Guides
                      - url: /docs/rex_book/index.html
                        title: Rex Book (work in progress)
                      - url: /docs/release_notes/index.html
                        title: Release notes
                      - url: https://metacpan.org/release/Rex
                        title: API
                        divider: 1
basic_app:
    class: Statocles::App::Basic
    args:
        store: 'content'
        url_root: '/'
        disable_content_template: 1
blog:
    class: Statocles::App::Blog
    args:
        store: 'blog'
        url_root: '/blog'
public:
    class: Statocles::App::Basic
    args:
        store: 'public'
        url_root: '/public'
gh_pages:
    class: Statocles::Deploy::Git
    args:
        branch: gh-pages
        base_url: https://rexify.org
rexify:
    class: Statocles::Theme
    args:
        store: theme
