site:
    class: Statocles::Site
    args:
        title: Rexify statocles
        base_url: https://rexops.github.io/rexify-website/
        theme:
            $ref: rexify
        apps:
            basic:
                $ref: basic_app
            public:
                $ref: public
        deploy:
            $ref: gh_pages
basic_app:
    class: Statocles::App::Basic
    args:
        store: 'content'
        url_root: '/'
        data:
            no_side_bar: 0
            trainings:
                date: 2018-08-26
                text: test training
            no_disqus: 1
public:
    class: Statocles::App::Basic
    args:
        store: 'public'
        url_root: '/public'
gh_pages:
    class: Statocles::Deploy::Git
    args:
        branch: gh-pages
        base_url: https://rexops.github.io/rexify-website/
rexify:
    class: Statocles::Theme
    args:
        store: theme
